### ISSUE TITLE
HTTPS verification is hardcoded to disabled in the requests calls

### ISSUE THREAD

**Issue by airhorns** [mtth/azkaban#16]
On https://github.com/mtth/azkaban/blob/f69e98db416d36a0288088364ad4b4e712c059a6/azkaban/remote.py#L44 SSL verification is hardcoded to off in the call to the `requests` library. This results in a bunch of `InsecureRequestWarning`s from `urllib3` in addition to it just being plain old unsafe. 

Can we remove the passing of that flag and let users configure urllib themselves if they want to disable SSL verification like that?

**Comment by mtth** [comment]
Sure. For backwards compatibility reasons, I'll keep `False` as default configuration option but could allow an override. Would setting the option when creating `Session` objects be enough for your use-case or would you like to be able to set it when using the CLI as well?

FYI, you can disable the warnings either by capturing them (see `azkaban.util.suppress_urllib_warnings` for an example) or by disabling them entirely (from `urllib` itself).

**Comment by airhorns** [comment]
Seems a bit sketchy to be unsafe by default, no? I don't think disabling them is a good idea for that same reason. It means you can get man in the middle'd or reveal all sorts of sensitive information while completely unaware. If you have a special config where you have self signed HTTPS certificates then I think it's a reasonable thing to expect to have to turn verification off but just doing it by default.

**Comment by mtth** [comment]
Yes, but it's important to not break existing clients. It'll be a bigger change then; I'll work on it.

**Comment by mtth** [comment]
Alright, versions `0.9.0` and up support toggling request verification (on by default).

To support this, aliases are now stored in a slightly different format (see the [documentation](http://azkabancli.readthedocs.org/en/latest/quickstart.html#urls-and-aliases) or aec0b688f2fe4832212c2f440a492839dabb7f07 for more info). Conversion from old to new format is handled transparently (turning verification off to ensure compatibility).

Let me know if you run into any issues.

**Comment by airhorns** [comment]
Thanks @mtth !!!
