### ISSUE TITLE
Create complex flows

### ISSUE THREAD

**Issue by memosstilvi** [mtth/azkaban#18]
Give the option to create complex flows that have multiple jobs that depend to each other. For example it would be really useful if we were able to generate job files like this: 

```
# foo.job
type=command
command=echo foo
```

```
# bar.job
type=command
dependencies=foo
command=echo bar
```

**Comment by sankethkatta** [comment]
You can generate those job files by simply by setting those properties exactly.
The [Job options](http://azkabancli.readthedocs.org/en/latest/quickstart.html#job-options) dictionary serializes directly to job files, with a few other niceties.

```python
from azkaban import Job, Project

PROJECT = Project('sample')

PROJECT.add_job('foo', Job({
  'type': 'command',
  'command': 'echo foo'
}))

PROJECT.add_job('bar', Job({
  'dependencies': 'foo',
  'type': 'command',
  'command': 'echo bar'
}))
```

**Comment by memosstilvi** [comment]
@sankethkatta Thanks a lot for the quick response. Will do that.
