### ISSUE TITLE
Support all concurrent choices

### ISSUE THREAD

**Issue by pmerienne** [mtth/azkaban#19]
When running a flow, azkaban-cli only support 'concurrent' and 'skip' values for the concurrentOption request parameters. However Azkaban server 3.0 supports 'skip', 'pipeline' and 'queue'.

It could be really great to supports all this values.

**Comment by mtth** [comment]
You're right, this would be good to have. I'll add this when I get a chance, thanks for bringing it up!

**Comment by mtth** [comment]
Just released `0.9.4` which should satisfy your use-case. Let me know if anything doesn't work.

**Comment by pmerienne** [comment]
Wow that was fast ! Thank you for this quick response.

However it could also be great to also support the pipelineLevel query parameter. (see https://github.com/azkaban/azkaban/blob/71b5dd9a83935c2f253b0d944e47909b918b06bc/azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java#L94)

I'll create a new pull-request for this.

Have a nice day
