### ISSUE TITLE
Support pipelineLevel to fully support all concurrent modes

### ISSUE THREAD

**Issue by pmerienne** [mtth/azkaban#20]
Hi,

It seems that the the lightweight azkaban client does not support the pipelineLevel query parameters (see https://github.com/azkaban/azkaban/blob/71b5dd9a83935c2f253b0d944e47909b918b06bc/azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java#L94). Enabling this will allow azkaban-cli to fully support all concurrent modes.

**Comment by mtth** [comment]
I'll see what I can do. There seems to also be a [`queueLevel`](https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java#L49) option. Would you be interested in that as well?

**Comment by pmerienne** [comment]
Actually, I'm not interested in the queue concurrent mode. But it could be nice to have it.
I may have some time to work on a PR for this issue. I'm not a good python dev. but I can try to do something great!
