### ISSUE TITLE
Creating Conditional Flow

### ISSUE THREAD

**Issue by drghifari** [mtth/azkaban#38]
Is there any chance we can create conditional flow on Job? https://azkaban.readthedocs.io/en/latest/conditionalFlow.html

**Comment by mtth** [comment]
I'm not familiar with this feature but there is a chance you can already use it by adding a `condition` entry to your jobs. Something like:

```python
conditional_job = Job({
  'type': 'command',
  'dependencies': 'JobA',
  'command': 'echo "Hello."',
  'condition': '${JobA:param1} == 1' # Job condition.
})
```
